{% set name = "google-cloud-error-reporting" %}
{% set version = "1.4.1" %}
{% set sha256 = "4a72a65586178daaacf6bbc4b718db0765b99a719fce88a95c2be4f82689b7c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-cloud-logging >=1.14.0,<2.5
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3

test:
  imports:
    - google.cloud.client
    - google.cloud.error_reporting

about:
  home: https://github.com/googleapis/python-error-reporting
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Stackdriver Error Reporting API client library
  description: "The Stackdriver Error Reporting API counts, analyzes and aggregates the crashes in your running cloud services. A centralized error management interface displays the results with sorting and filtering capabilities. Opt-in to receive email and mobile alerts on new errors.\nSee the [quick start guide](https://googleapis.dev/python/clouderrorreporting/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/clouderrorreporting/latest/index.html
  dev_url: https://github.com/googleapis/python-error-reporting

extra:
  recipe-maintainers:
    - parthea
